apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dotnet-app
  labels:
    app: my-dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-dotnet-app
  template:
    metadata:
      labels:
        app: my-dotnet-app
    spec:
      containers:
      - name: my-dotnet-app
        image: bhhelloworld.azurecr.io/mydotnetapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-dotnet-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-dotnet-app
