name: Build and Deploy to EKS
 
on:
#   push:
#     branches:
#       - master
  workflow_dispatch:
  workflow_call:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
 
      # Step 3: Build the application
      - name: Build project
        run: dotnet build --configuration Release -o ./MyNetApp/output
 
      # Step 4: Publish the artifact
      - name: Publish project
        run: dotnet publish -c Release -o ./MyNetApp/output
 
      # Step 5: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
 
      # Step 6: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest ./MyNetApp
 
      # Step 7: Push Image to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 994536024037.dkr.ecr.eu-north-1.amazonaws.com
      - name: Tag and Push Docker Image
        run: |
          docker tag myapp:latest 994536024037.dkr.ecr.eu-north-1.amazonaws.com/myapp:${{ github.sha }}
          docker push 994536024037.dkr.ecr.eu-north-1.amazonaws.com/myapp:${{ github.sha }}
 
      # Step 8: Deploy to EKS 
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region eu-north-1 --name my-eks-cluster
      - name: Deploy to EKS
        run: |
          kubectl apply -f deploymentEKS.yml
