name: Build, Push to ACR, and Deploy to AKS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-artifact:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET SDK
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the application
    - name: Build application
      run: dotnet build --configuration Release

    # Publish the application
    - name: Publish application
      run: dotnet publish --configuration Release -o ./publish

    # Upload the publish folder as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish-folder
        path: ./publish

  build-and-push-container:
    runs-on: ubuntu-latest
    needs: build-and-artifact

    steps:
    # Download the artifact
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: publish-folder

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }} ./publish

    # Push Docker Image to ACR
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/mydotnetapp:${{ github.sha }}

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push-container

    steps:
    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Get AKS credentials
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Deploy to AKS
    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml
