name: Build and Deploy to EKS
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Step 2: Setup AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
 
      # Step 3: Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest ./MyNetApp
 
      # Step 4: Push Image to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 994536024037.dkr.ecr.eu-north-1.amazonaws.com
      - name: Tag and Push Docker Image
        run: |
          docker tag myapp:latest 994536024037.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest
          docker push 994536024037.dkr.ecr.eu-north-1.amazonaws.com/myapp:latest
 
      # Step 5: Deploy to EKS
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region eu-north-1 --name my-eks-cluster
      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yml
