name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_USERNAME >> secrets.txt
        echo $DOCKER_PASSWORD >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
