name: Show Me the S3cr3tz
on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DOCKER_USERNAME: ${{ secrets.AWS_ACCESS_KEY_ID }}
        DOCKER_PASSWORD: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      run: |
        echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
        echo ${{secrets.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'
