name: Reusable Deployment Workflow
 
on:
  workflow_call:
    inputs:
      cloud_provider:
        description: 'Target Cloud Provider (Azure or AWS)'
        required: true
        type: string
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Common Steps for Code Checkout and Build
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Build project
        run: dotnet build --configuration Release -o ./MyNetApp/output

      - name: Publish project
        run: dotnet publish -c Release -o ./MyNetApp/output
 
      # Common Docker Build Step
      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.sha }} ./MyNetApp
 
      # Push Docker Image to Registry (Conditional for Azure or AWS)
      - name: Push Docker Image
        run: |
          echo "Push docker image" 
 
      # Deployment Steps (Separate for Azure and AWS)
      - name: Deploy to Cloud
        run: | 
          echo "Cloud deployment" 
      
      - name: Deploy to WebApp
        run: |
          if [[ "${{ inputs.cloud_provider }}" == "Azure" ]]; then
            echo "Deploying to Azure Web App Service..."
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
              slot-name: production
              images: bhhelloworld.azurecr.io/myapp:${{ github.sha }}
          elif [[ "${{ inputs.cloud_provider }}" == "AWS" ]]; then
            echo "Deploying to AWS..."
          else
            echo "Invalid cloud provider: ${{ inputs.cloud_provider }}"
            exit 1
          fi
